### ISSUE TITLE
Better usage string

### ISSUE THREAD

**Issue by mgill25** [kanishkdudeja/nginx-logs-replay#13]
In case no parameters are supplied, we just incrementally print the individual flag's error messages. Rather, I'd like to see a prettier, more sane usage format. The go command itself is a good example.

```
❯❯❯ go
    Go is a tool for managing Go source code.
    Usage

	go <command> [arguments]

    The commands are:

	bug         start a bug report

	build       compile packages and dependencies

```

**Comment by kanishkdudeja** [comment]
Yep, this will be a beautiful change 👍
