### ISSUE TITLE
Add Regex support for matching requests which need to be replayed

### ISSUE THREAD

**Issue by kanishkdudeja** [kanishkdudeja/nginx-logs-replay#9]
The current source code looks for the string: `GET /track` to filter requests which need to be replayed.

We should probably add Regex support so that users can any Regex pattern to filter as per their wish.

**Comment by kanishkdudeja** [comment]
On thinking more about this, the following approach seems reasonable to me:

`include-regex-pattern`: This configurable parameter will denote that we only need to replay requests which are matched by `include-regex-pattern`

`exclude-regex-pattern`: This configurable parameter will denote that we do not need to replay requests which are matched by `exclude-regex-pattern`

If the user uses both these configuration parameters, then one way of looking at it would be:

For each log line which match `include-regex-pattern`
{
    Exclude log line which matches `exclude-regex-pattern`
    {
         replay-request
    }
}

What do you think @mgill25 ?

**Comment by mgill25** [comment]
Seems reasonable, but I have one doubt: Why should exclude be given priority over include? If same regex is added to both include and exclude, what should we do? For each line which matches exclude, if it is also in include, maybe we prioritize that? Etc.

Lets take a look at how other tools solve this? I'm sure ack/silver search/ripgrep et all will have these filters and some way to resolve these conflicts.

**Comment by kanishkdudeja** [comment]
Makes sense. I'll look into this and update this issue thread.

**Comment by kanishkdudeja** [comment]
So, I looked into `ripgrep` and it only supports only one functionality at once. Meaning that:

- You can either use `rg regex_pattern`
- Or use `rg -v regex_pattern`. The `-v` flag is used for an inverse match, meaning if the regex pattern doesn't match the target.

This seems a reasonable way to go forward for v1. Though, I will look into other tools as well to see if we can come up with something better.

If not, we can allow the user to use either of these at once:

- `regex-match-filter`: Replay the request if the log line matches the provided the regex pattern
- `regex-match-exclude`: Replay the request if the log line doesn't match the provided regex pattern

**Comment by kanishkdudeja** [comment]
@mgill25 It looks like ack also supports only one functionality being used at once.

So, we can finalize on this - unless you have an objection.

**Comment by kanishkdudeja** [comment]
Merged in PR #20
